### ISSUE TITLE
TypeError: Cannot read property 'baseName' of undefined

### ISSUE THREAD

**Issue by noahsw** [rayokota/generator-angular-express-sequelize#8]
````
$ npm install -g generator-angular-express-sequelize
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-angular-express-sequelize will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
generator-angular-express-sequelize@0.1.12 /usr/local/lib/node_modules/generator-angular-express-sequelize
├── pluralize@0.0.12
├── URIjs@1.11.2
├── underscore.string@2.3.3
├── lodash@2.4.2
├── asciify@1.3.5 (pad@0.0.4, chalk@0.3.0, optimist@0.6.1)
└── yeoman-generator@0.14.2 (dargs@0.1.0, debug@0.7.4, diff@1.0.8, rimraf@2.2.8, text-table@0.2.0, mime@1.2.11, mkdirp@0.3.5, async@0.2.10, isbinaryfile@0.1.9, shelljs@0.2.6, chalk@0.3.0, iconv-lite@0.2.11, lodash@2.2.1, findup-sync@0.1.3, file-utils@0.1.5, glob@3.2.11, request@2.27.0, cheerio@0.12.4, inquirer@0.3.5, download@0.1.19)


$ yo angular-express-sequelize:entity user
You called the entity subgenerator with the argument user.

Please specify an attribute:
[?] What is the name of the attribute? (myattr) Error: Error: ENOENT, open 'generator.json'
[?] What is the name of the attribute? id
[?] What is the type of the attribute? Integer
[?] Enter the minimum value for the numeric attribute, or hit enter:
[?] Enter the maximum value for the numeric attribute, or hit enter:
[?] Is the attribute required to have a value? Yes
[?] Would you like to enter another attribute or reenter a previous attribute? Yes

Please specify an attribute:
[?] What is the name of the attribute? username
[?] What is the type of the attribute? String
[?] Enter the minimum length for the String attribute, or hit enter:
[?] Enter the maximum length for the String attribute, or hit enter:
[?] Is the attribute required to have a value? Yes
[?] Would you like to enter another attribute or reenter a previous attribute? Yes

Please specify an attribute:
[?] What is the name of the attribute? password
[?] What is the type of the attribute? String
[?] Enter the minimum length for the String attribute, or hit enter:
[?] Enter the maximum length for the String attribute, or hit enter:
[?] Is the attribute required to have a value? Yes
[?] Would you like to enter another attribute or reenter a previous attribute? No
/usr/local/lib/node_modules/generator-angular-express-sequelize/entity/index.js:151
  this.baseName = this.generatorConfig.baseName;
                                      ^
TypeError: Cannot read property 'baseName' of undefined
    at EntityGenerator.files (/usr/local/lib/node_modules/generator-angular-express-sequelize/entity/index.js:151:39)
    at /usr/local/lib/node_modules/generator-angular-express-sequelize/node_modules/yeoman-generator/lib/base.js:316:43
    at /usr/local/lib/node_modules/generator-angular-express-sequelize/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /usr/local/lib/node_modules/generator-angular-express-sequelize/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/usr/local/lib/node_modules/generator-angular-express-sequelize/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
    at /usr/local/lib/node_modules/generator-angular-express-sequelize/node_modules/yeoman-generator/node_modules/async/lib/async.js:145:25
    at /usr/local/lib/node_modules/generator-angular-express-sequelize/node_modules/yeoman-generator/node_modules/async/lib/async.js:229:17
    at /usr/local/lib/node_modules/generator-angular-express-sequelize/node_modules/yeoman-generator/node_modules/async/lib/async.js:556:34
    at /usr/local/lib/node_modules/generator-angular-express-sequelize/node_modules/yeoman-generator/lib/base.js:302:11
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/generator-angular-express-sequelize/node_modules/yeoman-generator/lib/util/conflicter.js:73:5)
````

**Comment by rayokota** [comment]
As mentioned in the README, you need to run 'yo angular-express-sequelize' first.
